# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/BasicConfigVersion-ExactVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeCInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeCXXInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeCommonLanguageInclude.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeGenericSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeInitializeConfigs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeLanguageInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeSystemSpecificInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/CMakeSystemSpecificInitialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Compiler/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Compiler/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Compiler/CMakeCommonCompilerMacros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Compiler/GNU.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Internal/CMakeCLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Internal/CMakeCXXLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Internal/CMakeCommonLinkerInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Linker/AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Linker/AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Linker/AppleClang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Apple-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Apple-Clang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Apple-Clang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Apple-Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Darwin-Initialize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Darwin.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Linker/Apple-AppleClang-C.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Linker/Apple-AppleClang-CXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/Linker/Apple-AppleClang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/Platform/UnixPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-4.2/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/Untitled/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/CMakeFiles/4.2.3/CMakeCCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/CMakeFiles/4.2.3/CMakeCXXCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/CMakeFiles/4.2.3/CMakeSystem.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/juce/tools/JUCEToolsExport.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/extras/Build/CMake/JUCECheckAtomic.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/extras/Build/CMake/JUCEConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/extras/Build/CMake/JUCEHelperTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/extras/Build/CMake/JUCEModuleSupport.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/extras/Build/CMake/JUCEUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/extras/Build/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/extras/Build/juceaide/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/JUCE/modules/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/Applications/CMake.app/Contents/bin/cmake -P /Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/CMakeFiles/VerifyGlobs.cmake

/Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -S/Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/Untitled -B/Users/victorschulhoff/Desktop/Delay-Grain/Delay\ Grain/v4
